// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `FaceRecognitionTrain.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____FaceRecognitionTrain_h__
#define ____FaceRecognitionTrain_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace RoboCompFaceRecognitionTrain
{

class FaceRecognitionTrain;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompFaceRecognitionTrain::FaceRecognitionTrain>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompFaceRecognitionTrain::FaceRecognitionTrain*);

}

}

namespace RoboCompFaceRecognitionTrain
{

class FaceRecognitionTrain;
bool operator==(const FaceRecognitionTrain&, const FaceRecognitionTrain&);
bool operator<(const FaceRecognitionTrain&, const FaceRecognitionTrain&);
::Ice::Object* upCast(::RoboCompFaceRecognitionTrain::FaceRecognitionTrain*);
typedef ::IceInternal::Handle< ::RoboCompFaceRecognitionTrain::FaceRecognitionTrain> FaceRecognitionTrainPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompFaceRecognitionTrain::FaceRecognitionTrain> FaceRecognitionTrainPrx;
void __patch(FaceRecognitionTrainPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompFaceRecognitionTrain
{

}

namespace IceProxy
{

namespace RoboCompFaceRecognitionTrain
{

class FaceRecognitionTrain : virtual public ::IceProxy::Ice::Object
{
public:
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_secure(bool __secure) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_twoway() const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_oneway() const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_batchOneway() const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_datagram() const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_batchDatagram() const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_compress(bool __compress) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_timeout(int __timeout) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<FaceRecognitionTrain> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<FaceRecognitionTrain*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace RoboCompFaceRecognitionTrain
{

class FaceRecognitionTrain : virtual public ::IceDelegate::Ice::Object
{
public:
};

}

}

namespace IceDelegateM
{

namespace RoboCompFaceRecognitionTrain
{

class FaceRecognitionTrain : virtual public ::IceDelegate::RoboCompFaceRecognitionTrain::FaceRecognitionTrain,
                             virtual public ::IceDelegateM::Ice::Object
{
public:
};

}

}

namespace IceDelegateD
{

namespace RoboCompFaceRecognitionTrain
{

class FaceRecognitionTrain : virtual public ::IceDelegate::RoboCompFaceRecognitionTrain::FaceRecognitionTrain,
                             virtual public ::IceDelegateD::Ice::Object
{
public:
};

}

}

namespace RoboCompFaceRecognitionTrain
{

class FaceRecognitionTrain : virtual public ::Ice::Object
{
public:

    typedef FaceRecognitionTrainPrx ProxyType;
    typedef FaceRecognitionTrainPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const FaceRecognitionTrain& l, const FaceRecognitionTrain& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const FaceRecognitionTrain& l, const FaceRecognitionTrain& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace RoboCompFaceRecognitionTrain
{

}

#endif
