// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `FaceRecognitionTrain.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <FaceRecognitionTrain.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompFaceRecognitionTrain::upCast(::IceProxy::RoboCompFaceRecognitionTrain::FaceRecognitionTrain* p) { return p; }

void
::IceProxy::RoboCompFaceRecognitionTrain::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompFaceRecognitionTrain::FaceRecognitionTrain>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompFaceRecognitionTrain::FaceRecognitionTrain;
        v->__copyFrom(proxy);
    }
}

const ::std::string&
IceProxy::RoboCompFaceRecognitionTrain::FaceRecognitionTrain::ice_staticId()
{
    return ::RoboCompFaceRecognitionTrain::FaceRecognitionTrain::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompFaceRecognitionTrain::FaceRecognitionTrain::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompFaceRecognitionTrain::FaceRecognitionTrain);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompFaceRecognitionTrain::FaceRecognitionTrain::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompFaceRecognitionTrain::FaceRecognitionTrain);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompFaceRecognitionTrain::FaceRecognitionTrain::__newInstance() const
{
    return new FaceRecognitionTrain;
}

::Ice::Object* RoboCompFaceRecognitionTrain::upCast(::RoboCompFaceRecognitionTrain::FaceRecognitionTrain* p) { return p; }

namespace
{
const ::std::string __RoboCompFaceRecognitionTrain__FaceRecognitionTrain_ids[2] =
{
    "::Ice::Object",
    "::RoboCompFaceRecognitionTrain::FaceRecognitionTrain"
};

}

bool
RoboCompFaceRecognitionTrain::FaceRecognitionTrain::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompFaceRecognitionTrain__FaceRecognitionTrain_ids, __RoboCompFaceRecognitionTrain__FaceRecognitionTrain_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompFaceRecognitionTrain::FaceRecognitionTrain::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompFaceRecognitionTrain__FaceRecognitionTrain_ids[0], &__RoboCompFaceRecognitionTrain__FaceRecognitionTrain_ids[2]);
}

const ::std::string&
RoboCompFaceRecognitionTrain::FaceRecognitionTrain::ice_id(const ::Ice::Current&) const
{
    return __RoboCompFaceRecognitionTrain__FaceRecognitionTrain_ids[1];
}

const ::std::string&
RoboCompFaceRecognitionTrain::FaceRecognitionTrain::ice_staticId()
{
    return __RoboCompFaceRecognitionTrain__FaceRecognitionTrain_ids[1];
}

void
RoboCompFaceRecognitionTrain::FaceRecognitionTrain::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompFaceRecognitionTrain::FaceRecognitionTrain::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompFaceRecognitionTrain::__patch(FaceRecognitionTrainPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompFaceRecognitionTrain::FaceRecognitionTrainPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompFaceRecognitionTrain::FaceRecognitionTrain::ice_staticId(), v);
    }
}
