// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `MSKFace.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <MSKFace.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompMSKFace__MSKFaceEvent__newFaceAvailable_name = "newFaceAvailable";

const ::std::string __RoboCompMSKFace__MSKFace__getFaces_name = "getFaces";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompMSKFace::upCast(::IceProxy::RoboCompMSKFace::MSKFaceEvent* p) { return p; }

void
::IceProxy::RoboCompMSKFace::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompMSKFace::MSKFaceEvent>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompMSKFace::MSKFaceEvent;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompMSKFace::MSKFaceEvent::newFaceAvailable(const ::RoboCompMSKFace::DetailedFaceMap& face, ::Ice::Long timestamp, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompMSKFace__MSKFaceEvent__newFaceAvailable_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompMSKFace::MSKFaceEvent* __del = dynamic_cast< ::IceDelegate::RoboCompMSKFace::MSKFaceEvent*>(__delBase.get());
            __del->newFaceAvailable(face, timestamp, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompMSKFace::MSKFaceEvent::begin_newFaceAvailable(const ::RoboCompMSKFace::DetailedFaceMap& face, ::Ice::Long timestamp, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompMSKFace__MSKFaceEvent__newFaceAvailable_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompMSKFace__MSKFaceEvent__newFaceAvailable_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(face);
        __os->write(timestamp);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompMSKFace::MSKFaceEvent::end_newFaceAvailable(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompMSKFace__MSKFaceEvent__newFaceAvailable_name);
}

const ::std::string&
IceProxy::RoboCompMSKFace::MSKFaceEvent::ice_staticId()
{
    return ::RoboCompMSKFace::MSKFaceEvent::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompMSKFace::MSKFaceEvent::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompMSKFace::MSKFaceEvent);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompMSKFace::MSKFaceEvent::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompMSKFace::MSKFaceEvent);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompMSKFace::MSKFaceEvent::__newInstance() const
{
    return new MSKFaceEvent;
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompMSKFace::upCast(::IceProxy::RoboCompMSKFace::MSKFace* p) { return p; }

void
::IceProxy::RoboCompMSKFace::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompMSKFace::MSKFace>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompMSKFace::MSKFace;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompMSKFace::MSKFace::getFaces(::RoboCompMSKFace::DetailedFaceMap& faces, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompMSKFace__MSKFace__getFaces_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompMSKFace__MSKFace__getFaces_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompMSKFace::MSKFace* __del = dynamic_cast< ::IceDelegate::RoboCompMSKFace::MSKFace*>(__delBase.get());
            __del->getFaces(faces, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompMSKFace::MSKFace::begin_getFaces(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompMSKFace__MSKFace__getFaces_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompMSKFace__MSKFace__getFaces_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompMSKFace__MSKFace__getFaces_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompMSKFace::MSKFace::end_getFaces(::RoboCompMSKFace::DetailedFaceMap& faces, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompMSKFace__MSKFace__getFaces_name);
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(faces);
        __result->__endReadParams();
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::RoboCompMSKFace::MSKFace::ice_staticId()
{
    return ::RoboCompMSKFace::MSKFace::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompMSKFace::MSKFace::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompMSKFace::MSKFace);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompMSKFace::MSKFace::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompMSKFace::MSKFace);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompMSKFace::MSKFace::__newInstance() const
{
    return new MSKFace;
}

void
IceDelegateM::RoboCompMSKFace::MSKFaceEvent::newFaceAvailable(const ::RoboCompMSKFace::DetailedFaceMap& face, ::Ice::Long timestamp, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompMSKFace__MSKFaceEvent__newFaceAvailable_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(face);
        __os->write(timestamp);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::RoboCompMSKFace::MSKFace::getFaces(::RoboCompMSKFace::DetailedFaceMap& faces, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompMSKFace__MSKFace__getFaces_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(faces);
        __og.endReadParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateD::RoboCompMSKFace::MSKFaceEvent::newFaceAvailable(const ::RoboCompMSKFace::DetailedFaceMap& face, ::Ice::Long timestamp, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompMSKFace::DetailedFaceMap& __p_face, ::Ice::Long __p_timestamp, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_face(__p_face),
            _m_timestamp(__p_timestamp)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompMSKFace::MSKFaceEvent* servant = dynamic_cast< ::RoboCompMSKFace::MSKFaceEvent*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->newFaceAvailable(_m_face, _m_timestamp, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompMSKFace::DetailedFaceMap& _m_face;
        ::Ice::Long _m_timestamp;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompMSKFace__MSKFaceEvent__newFaceAvailable_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(face, timestamp, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompMSKFace::MSKFace::getFaces(::RoboCompMSKFace::DetailedFaceMap& faces, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::RoboCompMSKFace::DetailedFaceMap& __p_faces, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_faces(__p_faces)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompMSKFace::MSKFace* servant = dynamic_cast< ::RoboCompMSKFace::MSKFace*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->getFaces(_m_faces, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::RoboCompMSKFace::DetailedFaceMap& _m_faces;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompMSKFace__MSKFace__getFaces_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(faces, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* RoboCompMSKFace::upCast(::RoboCompMSKFace::MSKFaceEvent* p) { return p; }

namespace
{
const ::std::string __RoboCompMSKFace__MSKFaceEvent_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMSKFace::MSKFaceEvent"
};

}

bool
RoboCompMSKFace::MSKFaceEvent::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompMSKFace__MSKFaceEvent_ids, __RoboCompMSKFace__MSKFaceEvent_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompMSKFace::MSKFaceEvent::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompMSKFace__MSKFaceEvent_ids[0], &__RoboCompMSKFace__MSKFaceEvent_ids[2]);
}

const ::std::string&
RoboCompMSKFace::MSKFaceEvent::ice_id(const ::Ice::Current&) const
{
    return __RoboCompMSKFace__MSKFaceEvent_ids[1];
}

const ::std::string&
RoboCompMSKFace::MSKFaceEvent::ice_staticId()
{
    return __RoboCompMSKFace__MSKFaceEvent_ids[1];
}

::Ice::DispatchStatus
RoboCompMSKFace::MSKFaceEvent::___newFaceAvailable(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompMSKFace::DetailedFaceMap face;
    ::Ice::Long timestamp;
    __is->read(face);
    __is->read(timestamp);
    __inS.endReadParams();
    newFaceAvailable(face, timestamp, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompMSKFace__MSKFaceEvent_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newFaceAvailable"
};

}

::Ice::DispatchStatus
RoboCompMSKFace::MSKFaceEvent::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompMSKFace__MSKFaceEvent_all, __RoboCompMSKFace__MSKFaceEvent_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompMSKFace__MSKFaceEvent_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___newFaceAvailable(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompMSKFace::MSKFaceEvent::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompMSKFace::MSKFaceEvent::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompMSKFace::__patch(MSKFaceEventPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompMSKFace::MSKFaceEventPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompMSKFace::MSKFaceEvent::ice_staticId(), v);
    }
}

::Ice::Object* RoboCompMSKFace::upCast(::RoboCompMSKFace::MSKFace* p) { return p; }

namespace
{
const ::std::string __RoboCompMSKFace__MSKFace_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMSKFace::MSKFace"
};

}

bool
RoboCompMSKFace::MSKFace::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompMSKFace__MSKFace_ids, __RoboCompMSKFace__MSKFace_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompMSKFace::MSKFace::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompMSKFace__MSKFace_ids[0], &__RoboCompMSKFace__MSKFace_ids[2]);
}

const ::std::string&
RoboCompMSKFace::MSKFace::ice_id(const ::Ice::Current&) const
{
    return __RoboCompMSKFace__MSKFace_ids[1];
}

const ::std::string&
RoboCompMSKFace::MSKFace::ice_staticId()
{
    return __RoboCompMSKFace__MSKFace_ids[1];
}

::Ice::DispatchStatus
RoboCompMSKFace::MSKFace::___getFaces(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompMSKFace::DetailedFaceMap faces;
    getFaces(faces, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(faces);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompMSKFace__MSKFace_all[] =
{
    "getFaces",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
RoboCompMSKFace::MSKFace::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompMSKFace__MSKFace_all, __RoboCompMSKFace__MSKFace_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompMSKFace__MSKFace_all)
    {
        case 0:
        {
            return ___getFaces(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompMSKFace::MSKFace::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompMSKFace::MSKFace::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompMSKFace::__patch(MSKFacePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompMSKFace::MSKFacePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompMSKFace::MSKFace::ice_staticId(), v);
    }
}
