// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `MSKRGBD.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <MSKRGBD.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompMSKRGBD__MSKRGBDEvent__newRGBImageAvailable_name = "newRGBImageAvailable";

const ::std::string __RoboCompMSKRGBD__MSKRGBDEvent__newDepthImageAvailable_name = "newDepthImageAvailable";

const ::std::string __RoboCompMSKRGBD__MSKRGBD__getRGBImage_name = "getRGBImage";

const ::std::string __RoboCompMSKRGBD__MSKRGBD__getDepthImage_name = "getDepthImage";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompMSKRGBD::upCast(::IceProxy::RoboCompMSKRGBD::MSKRGBDEvent* p) { return p; }

void
::IceProxy::RoboCompMSKRGBD::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompMSKRGBD::MSKRGBDEvent>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompMSKRGBD::MSKRGBDEvent;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompMSKRGBD::MSKRGBDEvent::newRGBImageAvailable(const ::RoboCompMSKRGBD::TRGBImage& RGBImage, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompMSKRGBD__MSKRGBDEvent__newRGBImageAvailable_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompMSKRGBD::MSKRGBDEvent* __del = dynamic_cast< ::IceDelegate::RoboCompMSKRGBD::MSKRGBDEvent*>(__delBase.get());
            __del->newRGBImageAvailable(RGBImage, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompMSKRGBD::MSKRGBDEvent::begin_newRGBImageAvailable(const ::RoboCompMSKRGBD::TRGBImage& RGBImage, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompMSKRGBD__MSKRGBDEvent__newRGBImageAvailable_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompMSKRGBD__MSKRGBDEvent__newRGBImageAvailable_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(RGBImage);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompMSKRGBD::MSKRGBDEvent::end_newRGBImageAvailable(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompMSKRGBD__MSKRGBDEvent__newRGBImageAvailable_name);
}

void
IceProxy::RoboCompMSKRGBD::MSKRGBDEvent::newDepthImageAvailable(const ::RoboCompMSKRGBD::TDepthImage& depthImage, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompMSKRGBD__MSKRGBDEvent__newDepthImageAvailable_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompMSKRGBD::MSKRGBDEvent* __del = dynamic_cast< ::IceDelegate::RoboCompMSKRGBD::MSKRGBDEvent*>(__delBase.get());
            __del->newDepthImageAvailable(depthImage, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompMSKRGBD::MSKRGBDEvent::begin_newDepthImageAvailable(const ::RoboCompMSKRGBD::TDepthImage& depthImage, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompMSKRGBD__MSKRGBDEvent__newDepthImageAvailable_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompMSKRGBD__MSKRGBDEvent__newDepthImageAvailable_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(depthImage);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompMSKRGBD::MSKRGBDEvent::end_newDepthImageAvailable(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompMSKRGBD__MSKRGBDEvent__newDepthImageAvailable_name);
}

const ::std::string&
IceProxy::RoboCompMSKRGBD::MSKRGBDEvent::ice_staticId()
{
    return ::RoboCompMSKRGBD::MSKRGBDEvent::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompMSKRGBD::MSKRGBDEvent::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompMSKRGBD::MSKRGBDEvent);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompMSKRGBD::MSKRGBDEvent::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompMSKRGBD::MSKRGBDEvent);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompMSKRGBD::MSKRGBDEvent::__newInstance() const
{
    return new MSKRGBDEvent;
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompMSKRGBD::upCast(::IceProxy::RoboCompMSKRGBD::MSKRGBD* p) { return p; }

void
::IceProxy::RoboCompMSKRGBD::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompMSKRGBD::MSKRGBD>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompMSKRGBD::MSKRGBD;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompMSKRGBD::MSKRGBD::getRGBImage(::RoboCompMSKRGBD::TRGBImage& RGBImage, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompMSKRGBD__MSKRGBD__getRGBImage_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompMSKRGBD__MSKRGBD__getRGBImage_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompMSKRGBD::MSKRGBD* __del = dynamic_cast< ::IceDelegate::RoboCompMSKRGBD::MSKRGBD*>(__delBase.get());
            __del->getRGBImage(RGBImage, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompMSKRGBD::MSKRGBD::begin_getRGBImage(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompMSKRGBD__MSKRGBD__getRGBImage_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompMSKRGBD__MSKRGBD__getRGBImage_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompMSKRGBD__MSKRGBD__getRGBImage_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompMSKRGBD::MSKRGBD::end_getRGBImage(::RoboCompMSKRGBD::TRGBImage& RGBImage, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompMSKRGBD__MSKRGBD__getRGBImage_name);
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(RGBImage);
        __result->__endReadParams();
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

void
IceProxy::RoboCompMSKRGBD::MSKRGBD::getDepthImage(::RoboCompMSKRGBD::TDepthImage& depthImage, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompMSKRGBD__MSKRGBD__getDepthImage_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompMSKRGBD__MSKRGBD__getDepthImage_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompMSKRGBD::MSKRGBD* __del = dynamic_cast< ::IceDelegate::RoboCompMSKRGBD::MSKRGBD*>(__delBase.get());
            __del->getDepthImage(depthImage, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompMSKRGBD::MSKRGBD::begin_getDepthImage(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompMSKRGBD__MSKRGBD__getDepthImage_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompMSKRGBD__MSKRGBD__getDepthImage_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompMSKRGBD__MSKRGBD__getDepthImage_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompMSKRGBD::MSKRGBD::end_getDepthImage(::RoboCompMSKRGBD::TDepthImage& depthImage, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompMSKRGBD__MSKRGBD__getDepthImage_name);
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(depthImage);
        __result->__endReadParams();
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::RoboCompMSKRGBD::MSKRGBD::ice_staticId()
{
    return ::RoboCompMSKRGBD::MSKRGBD::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompMSKRGBD::MSKRGBD::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompMSKRGBD::MSKRGBD);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompMSKRGBD::MSKRGBD::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompMSKRGBD::MSKRGBD);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompMSKRGBD::MSKRGBD::__newInstance() const
{
    return new MSKRGBD;
}

void
IceDelegateM::RoboCompMSKRGBD::MSKRGBDEvent::newRGBImageAvailable(const ::RoboCompMSKRGBD::TRGBImage& RGBImage, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompMSKRGBD__MSKRGBDEvent__newRGBImageAvailable_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(RGBImage);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::RoboCompMSKRGBD::MSKRGBDEvent::newDepthImageAvailable(const ::RoboCompMSKRGBD::TDepthImage& depthImage, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompMSKRGBD__MSKRGBDEvent__newDepthImageAvailable_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(depthImage);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::RoboCompMSKRGBD::MSKRGBD::getRGBImage(::RoboCompMSKRGBD::TRGBImage& RGBImage, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompMSKRGBD__MSKRGBD__getRGBImage_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(RGBImage);
        __og.endReadParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::RoboCompMSKRGBD::MSKRGBD::getDepthImage(::RoboCompMSKRGBD::TDepthImage& depthImage, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompMSKRGBD__MSKRGBD__getDepthImage_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(depthImage);
        __og.endReadParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateD::RoboCompMSKRGBD::MSKRGBDEvent::newRGBImageAvailable(const ::RoboCompMSKRGBD::TRGBImage& RGBImage, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompMSKRGBD::TRGBImage& __p_RGBImage, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_RGBImage(__p_RGBImage)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompMSKRGBD::MSKRGBDEvent* servant = dynamic_cast< ::RoboCompMSKRGBD::MSKRGBDEvent*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->newRGBImageAvailable(_m_RGBImage, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompMSKRGBD::TRGBImage& _m_RGBImage;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompMSKRGBD__MSKRGBDEvent__newRGBImageAvailable_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(RGBImage, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompMSKRGBD::MSKRGBDEvent::newDepthImageAvailable(const ::RoboCompMSKRGBD::TDepthImage& depthImage, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompMSKRGBD::TDepthImage& __p_depthImage, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_depthImage(__p_depthImage)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompMSKRGBD::MSKRGBDEvent* servant = dynamic_cast< ::RoboCompMSKRGBD::MSKRGBDEvent*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->newDepthImageAvailable(_m_depthImage, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompMSKRGBD::TDepthImage& _m_depthImage;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompMSKRGBD__MSKRGBDEvent__newDepthImageAvailable_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(depthImage, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompMSKRGBD::MSKRGBD::getRGBImage(::RoboCompMSKRGBD::TRGBImage& RGBImage, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::RoboCompMSKRGBD::TRGBImage& __p_RGBImage, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_RGBImage(__p_RGBImage)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompMSKRGBD::MSKRGBD* servant = dynamic_cast< ::RoboCompMSKRGBD::MSKRGBD*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->getRGBImage(_m_RGBImage, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::RoboCompMSKRGBD::TRGBImage& _m_RGBImage;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompMSKRGBD__MSKRGBD__getRGBImage_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(RGBImage, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompMSKRGBD::MSKRGBD::getDepthImage(::RoboCompMSKRGBD::TDepthImage& depthImage, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::RoboCompMSKRGBD::TDepthImage& __p_depthImage, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_depthImage(__p_depthImage)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompMSKRGBD::MSKRGBD* servant = dynamic_cast< ::RoboCompMSKRGBD::MSKRGBD*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->getDepthImage(_m_depthImage, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::RoboCompMSKRGBD::TDepthImage& _m_depthImage;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompMSKRGBD__MSKRGBD__getDepthImage_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(depthImage, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* RoboCompMSKRGBD::upCast(::RoboCompMSKRGBD::MSKRGBDEvent* p) { return p; }

namespace
{
const ::std::string __RoboCompMSKRGBD__MSKRGBDEvent_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMSKRGBD::MSKRGBDEvent"
};

}

bool
RoboCompMSKRGBD::MSKRGBDEvent::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompMSKRGBD__MSKRGBDEvent_ids, __RoboCompMSKRGBD__MSKRGBDEvent_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompMSKRGBD::MSKRGBDEvent::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompMSKRGBD__MSKRGBDEvent_ids[0], &__RoboCompMSKRGBD__MSKRGBDEvent_ids[2]);
}

const ::std::string&
RoboCompMSKRGBD::MSKRGBDEvent::ice_id(const ::Ice::Current&) const
{
    return __RoboCompMSKRGBD__MSKRGBDEvent_ids[1];
}

const ::std::string&
RoboCompMSKRGBD::MSKRGBDEvent::ice_staticId()
{
    return __RoboCompMSKRGBD__MSKRGBDEvent_ids[1];
}

::Ice::DispatchStatus
RoboCompMSKRGBD::MSKRGBDEvent::___newRGBImageAvailable(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompMSKRGBD::TRGBImage RGBImage;
    __is->read(RGBImage);
    __inS.endReadParams();
    newRGBImageAvailable(RGBImage, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompMSKRGBD::MSKRGBDEvent::___newDepthImageAvailable(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompMSKRGBD::TDepthImage depthImage;
    __is->read(depthImage);
    __inS.endReadParams();
    newDepthImageAvailable(depthImage, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompMSKRGBD__MSKRGBDEvent_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newDepthImageAvailable",
    "newRGBImageAvailable"
};

}

::Ice::DispatchStatus
RoboCompMSKRGBD::MSKRGBDEvent::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompMSKRGBD__MSKRGBDEvent_all, __RoboCompMSKRGBD__MSKRGBDEvent_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompMSKRGBD__MSKRGBDEvent_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___newDepthImageAvailable(in, current);
        }
        case 5:
        {
            return ___newRGBImageAvailable(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompMSKRGBD::MSKRGBDEvent::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompMSKRGBD::MSKRGBDEvent::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompMSKRGBD::__patch(MSKRGBDEventPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompMSKRGBD::MSKRGBDEventPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompMSKRGBD::MSKRGBDEvent::ice_staticId(), v);
    }
}

::Ice::Object* RoboCompMSKRGBD::upCast(::RoboCompMSKRGBD::MSKRGBD* p) { return p; }

namespace
{
const ::std::string __RoboCompMSKRGBD__MSKRGBD_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMSKRGBD::MSKRGBD"
};

}

bool
RoboCompMSKRGBD::MSKRGBD::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompMSKRGBD__MSKRGBD_ids, __RoboCompMSKRGBD__MSKRGBD_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompMSKRGBD::MSKRGBD::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompMSKRGBD__MSKRGBD_ids[0], &__RoboCompMSKRGBD__MSKRGBD_ids[2]);
}

const ::std::string&
RoboCompMSKRGBD::MSKRGBD::ice_id(const ::Ice::Current&) const
{
    return __RoboCompMSKRGBD__MSKRGBD_ids[1];
}

const ::std::string&
RoboCompMSKRGBD::MSKRGBD::ice_staticId()
{
    return __RoboCompMSKRGBD__MSKRGBD_ids[1];
}

::Ice::DispatchStatus
RoboCompMSKRGBD::MSKRGBD::___getRGBImage(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompMSKRGBD::TRGBImage RGBImage;
    getRGBImage(RGBImage, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(RGBImage);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompMSKRGBD::MSKRGBD::___getDepthImage(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompMSKRGBD::TDepthImage depthImage;
    getDepthImage(depthImage, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(depthImage);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompMSKRGBD__MSKRGBD_all[] =
{
    "getDepthImage",
    "getRGBImage",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
RoboCompMSKRGBD::MSKRGBD::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompMSKRGBD__MSKRGBD_all, __RoboCompMSKRGBD__MSKRGBD_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompMSKRGBD__MSKRGBD_all)
    {
        case 0:
        {
            return ___getDepthImage(in, current);
        }
        case 1:
        {
            return ___getRGBImage(in, current);
        }
        case 2:
        {
            return ___ice_id(in, current);
        }
        case 3:
        {
            return ___ice_ids(in, current);
        }
        case 4:
        {
            return ___ice_isA(in, current);
        }
        case 5:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompMSKRGBD::MSKRGBD::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompMSKRGBD::MSKRGBD::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompMSKRGBD::__patch(MSKRGBDPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompMSKRGBD::MSKRGBDPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompMSKRGBD::MSKRGBD::ice_staticId(), v);
    }
}
