// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `InverseKinematics.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <InverseKinematics.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompInverseKinematics__InverseKinematics__getTargetState_name = "getTargetState";

const ::std::string __RoboCompInverseKinematics__InverseKinematics__setTargetPose6D_name = "setTargetPose6D";

const ::std::string __RoboCompInverseKinematics__InverseKinematics__setTargetAlignaxis_name = "setTargetAlignaxis";

const ::std::string __RoboCompInverseKinematics__InverseKinematics__setTargetAdvanceAxis_name = "setTargetAdvanceAxis";

const ::std::string __RoboCompInverseKinematics__InverseKinematics__getPartState_name = "getPartState";

const ::std::string __RoboCompInverseKinematics__InverseKinematics__goHome_name = "goHome";

const ::std::string __RoboCompInverseKinematics__InverseKinematics__stop_name = "stop";

const ::std::string __RoboCompInverseKinematics__InverseKinematics__setJoint_name = "setJoint";

const ::std::string __RoboCompInverseKinematics__InverseKinematics__setFingers_name = "setFingers";

}

namespace
{

const char* __RoboCompInverseKinematics__IKException_name = "RoboCompInverseKinematics::IKException";

struct __F__RoboCompInverseKinematics__IKException : public ::IceInternal::UserExceptionFactory
{
    virtual void
    createAndThrow(const ::std::string&)
    {
        throw ::RoboCompInverseKinematics::IKException();
    }
};

class __F__RoboCompInverseKinematics__IKException__Init
{
public:

    __F__RoboCompInverseKinematics__IKException__Init()
    {
        ::IceInternal::factoryTable->addExceptionFactory("::RoboCompInverseKinematics::IKException", new __F__RoboCompInverseKinematics__IKException);
    }

    ~__F__RoboCompInverseKinematics__IKException__Init()
    {
        ::IceInternal::factoryTable->removeExceptionFactory("::RoboCompInverseKinematics::IKException");
    }
};

const __F__RoboCompInverseKinematics__IKException__Init __F__RoboCompInverseKinematics__IKException__i;

}

RoboCompInverseKinematics::IKException::IKException(const ::std::string& __ice_text) :
    ::Ice::UserException(),
    text(__ice_text)
{
}

RoboCompInverseKinematics::IKException::~IKException() throw()
{
}

::std::string
RoboCompInverseKinematics::IKException::ice_name() const
{
    return __RoboCompInverseKinematics__IKException_name;
}

RoboCompInverseKinematics::IKException*
RoboCompInverseKinematics::IKException::ice_clone() const
{
    return new IKException(*this);
}

void
RoboCompInverseKinematics::IKException::ice_throw() const
{
    throw *this;
}

void
RoboCompInverseKinematics::IKException::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice("::RoboCompInverseKinematics::IKException", -1, true);
    __os->write(text);
    __os->endWriteSlice();
}

void
RoboCompInverseKinematics::IKException::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->read(text);
    __is->endReadSlice();
}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompInverseKinematics::upCast(::IceProxy::RoboCompInverseKinematics::InverseKinematics* p) { return p; }

void
::IceProxy::RoboCompInverseKinematics::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompInverseKinematics::InverseKinematics>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompInverseKinematics::InverseKinematics;
        v->__copyFrom(proxy);
    }
}

::RoboCompInverseKinematics::TargetState
IceProxy::RoboCompInverseKinematics::InverseKinematics::getTargetState(const ::std::string& bodyPart, ::Ice::Int targetID, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompInverseKinematics__InverseKinematics__getTargetState_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__getTargetState_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompInverseKinematics::InverseKinematics* __del = dynamic_cast< ::IceDelegate::RoboCompInverseKinematics::InverseKinematics*>(__delBase.get());
            return __del->getTargetState(bodyPart, targetID, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompInverseKinematics::InverseKinematics::begin_getTargetState(const ::std::string& bodyPart, ::Ice::Int targetID, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__getTargetState_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompInverseKinematics__InverseKinematics__getTargetState_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompInverseKinematics__InverseKinematics__getTargetState_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __os->write(targetID);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::RoboCompInverseKinematics::TargetState
IceProxy::RoboCompInverseKinematics::InverseKinematics::end_getTargetState(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompInverseKinematics__InverseKinematics__getTargetState_name);
    ::RoboCompInverseKinematics::TargetState __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::Ice::Int
IceProxy::RoboCompInverseKinematics::InverseKinematics::setTargetPose6D(const ::std::string& bodyPart, const ::RoboCompInverseKinematics::Pose6D& target, const ::RoboCompInverseKinematics::WeightVector& weights, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompInverseKinematics__InverseKinematics__setTargetPose6D_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__setTargetPose6D_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompInverseKinematics::InverseKinematics* __del = dynamic_cast< ::IceDelegate::RoboCompInverseKinematics::InverseKinematics*>(__delBase.get());
            return __del->setTargetPose6D(bodyPart, target, weights, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompInverseKinematics::InverseKinematics::begin_setTargetPose6D(const ::std::string& bodyPart, const ::RoboCompInverseKinematics::Pose6D& target, const ::RoboCompInverseKinematics::WeightVector& weights, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__setTargetPose6D_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompInverseKinematics__InverseKinematics__setTargetPose6D_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompInverseKinematics__InverseKinematics__setTargetPose6D_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __os->write(target);
        __os->write(weights);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Ice::Int
IceProxy::RoboCompInverseKinematics::InverseKinematics::end_setTargetPose6D(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompInverseKinematics__InverseKinematics__setTargetPose6D_name);
    ::Ice::Int __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::Ice::Int
IceProxy::RoboCompInverseKinematics::InverseKinematics::setTargetAlignaxis(const ::std::string& bodyPart, const ::RoboCompInverseKinematics::Pose6D& target, const ::RoboCompInverseKinematics::Axis& ax, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompInverseKinematics__InverseKinematics__setTargetAlignaxis_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__setTargetAlignaxis_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompInverseKinematics::InverseKinematics* __del = dynamic_cast< ::IceDelegate::RoboCompInverseKinematics::InverseKinematics*>(__delBase.get());
            return __del->setTargetAlignaxis(bodyPart, target, ax, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompInverseKinematics::InverseKinematics::begin_setTargetAlignaxis(const ::std::string& bodyPart, const ::RoboCompInverseKinematics::Pose6D& target, const ::RoboCompInverseKinematics::Axis& ax, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__setTargetAlignaxis_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompInverseKinematics__InverseKinematics__setTargetAlignaxis_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompInverseKinematics__InverseKinematics__setTargetAlignaxis_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __os->write(target);
        __os->write(ax);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Ice::Int
IceProxy::RoboCompInverseKinematics::InverseKinematics::end_setTargetAlignaxis(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompInverseKinematics__InverseKinematics__setTargetAlignaxis_name);
    ::Ice::Int __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::Ice::Int
IceProxy::RoboCompInverseKinematics::InverseKinematics::setTargetAdvanceAxis(const ::std::string& bodyPart, const ::RoboCompInverseKinematics::Axis& ax, ::Ice::Float dist, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompInverseKinematics__InverseKinematics__setTargetAdvanceAxis_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__setTargetAdvanceAxis_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompInverseKinematics::InverseKinematics* __del = dynamic_cast< ::IceDelegate::RoboCompInverseKinematics::InverseKinematics*>(__delBase.get());
            return __del->setTargetAdvanceAxis(bodyPart, ax, dist, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompInverseKinematics::InverseKinematics::begin_setTargetAdvanceAxis(const ::std::string& bodyPart, const ::RoboCompInverseKinematics::Axis& ax, ::Ice::Float dist, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__setTargetAdvanceAxis_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompInverseKinematics__InverseKinematics__setTargetAdvanceAxis_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompInverseKinematics__InverseKinematics__setTargetAdvanceAxis_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __os->write(ax);
        __os->write(dist);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Ice::Int
IceProxy::RoboCompInverseKinematics::InverseKinematics::end_setTargetAdvanceAxis(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompInverseKinematics__InverseKinematics__setTargetAdvanceAxis_name);
    ::Ice::Int __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

bool
IceProxy::RoboCompInverseKinematics::InverseKinematics::getPartState(const ::std::string& bodyPart, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompInverseKinematics__InverseKinematics__getPartState_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__getPartState_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompInverseKinematics::InverseKinematics* __del = dynamic_cast< ::IceDelegate::RoboCompInverseKinematics::InverseKinematics*>(__delBase.get());
            return __del->getPartState(bodyPart, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompInverseKinematics::InverseKinematics::begin_getPartState(const ::std::string& bodyPart, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__getPartState_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompInverseKinematics__InverseKinematics__getPartState_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompInverseKinematics__InverseKinematics__getPartState_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::RoboCompInverseKinematics::InverseKinematics::end_getPartState(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompInverseKinematics__InverseKinematics__getPartState_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

void
IceProxy::RoboCompInverseKinematics::InverseKinematics::goHome(const ::std::string& bodyPart, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompInverseKinematics__InverseKinematics__goHome_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__goHome_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompInverseKinematics::InverseKinematics* __del = dynamic_cast< ::IceDelegate::RoboCompInverseKinematics::InverseKinematics*>(__delBase.get());
            __del->goHome(bodyPart, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompInverseKinematics::InverseKinematics::begin_goHome(const ::std::string& bodyPart, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__goHome_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompInverseKinematics__InverseKinematics__goHome_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompInverseKinematics__InverseKinematics__goHome_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompInverseKinematics::InverseKinematics::end_goHome(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompInverseKinematics__InverseKinematics__goHome_name);
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        __result->__readEmptyParams();
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

void
IceProxy::RoboCompInverseKinematics::InverseKinematics::stop(const ::std::string& bodyPart, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompInverseKinematics__InverseKinematics__stop_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__stop_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompInverseKinematics::InverseKinematics* __del = dynamic_cast< ::IceDelegate::RoboCompInverseKinematics::InverseKinematics*>(__delBase.get());
            __del->stop(bodyPart, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompInverseKinematics::InverseKinematics::begin_stop(const ::std::string& bodyPart, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__stop_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompInverseKinematics__InverseKinematics__stop_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompInverseKinematics__InverseKinematics__stop_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompInverseKinematics::InverseKinematics::end_stop(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompInverseKinematics__InverseKinematics__stop_name);
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        __result->__readEmptyParams();
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

void
IceProxy::RoboCompInverseKinematics::InverseKinematics::setJoint(const ::std::string& joint, ::Ice::Float angle, ::Ice::Float maxSpeed, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompInverseKinematics__InverseKinematics__setJoint_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__setJoint_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompInverseKinematics::InverseKinematics* __del = dynamic_cast< ::IceDelegate::RoboCompInverseKinematics::InverseKinematics*>(__delBase.get());
            __del->setJoint(joint, angle, maxSpeed, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompInverseKinematics::InverseKinematics::begin_setJoint(const ::std::string& joint, ::Ice::Float angle, ::Ice::Float maxSpeed, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__setJoint_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompInverseKinematics__InverseKinematics__setJoint_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompInverseKinematics__InverseKinematics__setJoint_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(joint);
        __os->write(angle);
        __os->write(maxSpeed);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompInverseKinematics::InverseKinematics::end_setJoint(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompInverseKinematics__InverseKinematics__setJoint_name);
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        __result->__readEmptyParams();
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

void
IceProxy::RoboCompInverseKinematics::InverseKinematics::setFingers(::Ice::Float d, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompInverseKinematics__InverseKinematics__setFingers_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__setFingers_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompInverseKinematics::InverseKinematics* __del = dynamic_cast< ::IceDelegate::RoboCompInverseKinematics::InverseKinematics*>(__delBase.get());
            __del->setFingers(d, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompInverseKinematics::InverseKinematics::begin_setFingers(::Ice::Float d, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompInverseKinematics__InverseKinematics__setFingers_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompInverseKinematics__InverseKinematics__setFingers_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompInverseKinematics__InverseKinematics__setFingers_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(d);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompInverseKinematics::InverseKinematics::end_setFingers(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompInverseKinematics__InverseKinematics__setFingers_name);
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        __result->__readEmptyParams();
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::RoboCompInverseKinematics::InverseKinematics::ice_staticId()
{
    return ::RoboCompInverseKinematics::InverseKinematics::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompInverseKinematics::InverseKinematics::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompInverseKinematics::InverseKinematics);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompInverseKinematics::InverseKinematics::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompInverseKinematics::InverseKinematics);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompInverseKinematics::InverseKinematics::__newInstance() const
{
    return new InverseKinematics;
}

::RoboCompInverseKinematics::TargetState
IceDelegateM::RoboCompInverseKinematics::InverseKinematics::getTargetState(const ::std::string& bodyPart, ::Ice::Int targetID, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompInverseKinematics__InverseKinematics__getTargetState_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __os->write(targetID);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::RoboCompInverseKinematics::TargetState __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::Ice::Int
IceDelegateM::RoboCompInverseKinematics::InverseKinematics::setTargetPose6D(const ::std::string& bodyPart, const ::RoboCompInverseKinematics::Pose6D& target, const ::RoboCompInverseKinematics::WeightVector& weights, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompInverseKinematics__InverseKinematics__setTargetPose6D_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __os->write(target);
        __os->write(weights);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::Ice::Int __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::Ice::Int
IceDelegateM::RoboCompInverseKinematics::InverseKinematics::setTargetAlignaxis(const ::std::string& bodyPart, const ::RoboCompInverseKinematics::Pose6D& target, const ::RoboCompInverseKinematics::Axis& ax, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompInverseKinematics__InverseKinematics__setTargetAlignaxis_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __os->write(target);
        __os->write(ax);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::Ice::Int __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::Ice::Int
IceDelegateM::RoboCompInverseKinematics::InverseKinematics::setTargetAdvanceAxis(const ::std::string& bodyPart, const ::RoboCompInverseKinematics::Axis& ax, ::Ice::Float dist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompInverseKinematics__InverseKinematics__setTargetAdvanceAxis_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __os->write(ax);
        __os->write(dist);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::Ice::Int __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::RoboCompInverseKinematics::InverseKinematics::getPartState(const ::std::string& bodyPart, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompInverseKinematics__InverseKinematics__getPartState_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::RoboCompInverseKinematics::InverseKinematics::goHome(const ::std::string& bodyPart, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompInverseKinematics__InverseKinematics__goHome_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        __og.readEmptyParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::RoboCompInverseKinematics::InverseKinematics::stop(const ::std::string& bodyPart, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompInverseKinematics__InverseKinematics__stop_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(bodyPart);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        __og.readEmptyParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::RoboCompInverseKinematics::InverseKinematics::setJoint(const ::std::string& joint, ::Ice::Float angle, ::Ice::Float maxSpeed, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompInverseKinematics__InverseKinematics__setJoint_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(joint);
        __os->write(angle);
        __os->write(maxSpeed);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        __og.readEmptyParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::RoboCompInverseKinematics::InverseKinematics::setFingers(::Ice::Float d, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompInverseKinematics__InverseKinematics__setFingers_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(d);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::RoboCompInverseKinematics::IKException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        __og.readEmptyParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::RoboCompInverseKinematics::TargetState
IceDelegateD::RoboCompInverseKinematics::InverseKinematics::getTargetState(const ::std::string& bodyPart, ::Ice::Int targetID, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::RoboCompInverseKinematics::TargetState& __result, const ::std::string& __p_bodyPart, ::Ice::Int __p_targetID, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_bodyPart(__p_bodyPart),
            _m_targetID(__p_targetID)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompInverseKinematics::InverseKinematics* servant = dynamic_cast< ::RoboCompInverseKinematics::InverseKinematics*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->getTargetState(_m_bodyPart, _m_targetID, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::RoboCompInverseKinematics::TargetState& _result;
        const ::std::string& _m_bodyPart;
        ::Ice::Int _m_targetID;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompInverseKinematics__InverseKinematics__getTargetState_name, ::Ice::Normal, __context);
    ::RoboCompInverseKinematics::TargetState __result;
    try
    {
        _DirectI __direct(__result, bodyPart, targetID, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Int
IceDelegateD::RoboCompInverseKinematics::InverseKinematics::setTargetPose6D(const ::std::string& bodyPart, const ::RoboCompInverseKinematics::Pose6D& target, const ::RoboCompInverseKinematics::WeightVector& weights, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int& __result, const ::std::string& __p_bodyPart, const ::RoboCompInverseKinematics::Pose6D& __p_target, const ::RoboCompInverseKinematics::WeightVector& __p_weights, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_bodyPart(__p_bodyPart),
            _m_target(__p_target),
            _m_weights(__p_weights)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompInverseKinematics::InverseKinematics* servant = dynamic_cast< ::RoboCompInverseKinematics::InverseKinematics*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                _result = servant->setTargetPose6D(_m_bodyPart, _m_target, _m_weights, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        ::Ice::Int& _result;
        const ::std::string& _m_bodyPart;
        const ::RoboCompInverseKinematics::Pose6D& _m_target;
        const ::RoboCompInverseKinematics::WeightVector& _m_weights;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompInverseKinematics__InverseKinematics__setTargetPose6D_name, ::Ice::Normal, __context);
    ::Ice::Int __result;
    try
    {
        _DirectI __direct(__result, bodyPart, target, weights, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::RoboCompInverseKinematics::IKException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Int
IceDelegateD::RoboCompInverseKinematics::InverseKinematics::setTargetAlignaxis(const ::std::string& bodyPart, const ::RoboCompInverseKinematics::Pose6D& target, const ::RoboCompInverseKinematics::Axis& ax, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int& __result, const ::std::string& __p_bodyPart, const ::RoboCompInverseKinematics::Pose6D& __p_target, const ::RoboCompInverseKinematics::Axis& __p_ax, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_bodyPart(__p_bodyPart),
            _m_target(__p_target),
            _m_ax(__p_ax)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompInverseKinematics::InverseKinematics* servant = dynamic_cast< ::RoboCompInverseKinematics::InverseKinematics*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                _result = servant->setTargetAlignaxis(_m_bodyPart, _m_target, _m_ax, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        ::Ice::Int& _result;
        const ::std::string& _m_bodyPart;
        const ::RoboCompInverseKinematics::Pose6D& _m_target;
        const ::RoboCompInverseKinematics::Axis& _m_ax;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompInverseKinematics__InverseKinematics__setTargetAlignaxis_name, ::Ice::Normal, __context);
    ::Ice::Int __result;
    try
    {
        _DirectI __direct(__result, bodyPart, target, ax, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::RoboCompInverseKinematics::IKException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Int
IceDelegateD::RoboCompInverseKinematics::InverseKinematics::setTargetAdvanceAxis(const ::std::string& bodyPart, const ::RoboCompInverseKinematics::Axis& ax, ::Ice::Float dist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int& __result, const ::std::string& __p_bodyPart, const ::RoboCompInverseKinematics::Axis& __p_ax, ::Ice::Float __p_dist, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_bodyPart(__p_bodyPart),
            _m_ax(__p_ax),
            _m_dist(__p_dist)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompInverseKinematics::InverseKinematics* servant = dynamic_cast< ::RoboCompInverseKinematics::InverseKinematics*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                _result = servant->setTargetAdvanceAxis(_m_bodyPart, _m_ax, _m_dist, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        ::Ice::Int& _result;
        const ::std::string& _m_bodyPart;
        const ::RoboCompInverseKinematics::Axis& _m_ax;
        ::Ice::Float _m_dist;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompInverseKinematics__InverseKinematics__setTargetAdvanceAxis_name, ::Ice::Normal, __context);
    ::Ice::Int __result;
    try
    {
        _DirectI __direct(__result, bodyPart, ax, dist, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::RoboCompInverseKinematics::IKException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::RoboCompInverseKinematics::InverseKinematics::getPartState(const ::std::string& bodyPart, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::std::string& __p_bodyPart, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_bodyPart(__p_bodyPart)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompInverseKinematics::InverseKinematics* servant = dynamic_cast< ::RoboCompInverseKinematics::InverseKinematics*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                _result = servant->getPartState(_m_bodyPart, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        bool& _result;
        const ::std::string& _m_bodyPart;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompInverseKinematics__InverseKinematics__getPartState_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, bodyPart, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::RoboCompInverseKinematics::IKException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

void
IceDelegateD::RoboCompInverseKinematics::InverseKinematics::goHome(const ::std::string& bodyPart, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& __p_bodyPart, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_bodyPart(__p_bodyPart)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompInverseKinematics::InverseKinematics* servant = dynamic_cast< ::RoboCompInverseKinematics::InverseKinematics*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                servant->goHome(_m_bodyPart, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        const ::std::string& _m_bodyPart;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompInverseKinematics__InverseKinematics__goHome_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(bodyPart, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::RoboCompInverseKinematics::IKException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompInverseKinematics::InverseKinematics::stop(const ::std::string& bodyPart, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& __p_bodyPart, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_bodyPart(__p_bodyPart)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompInverseKinematics::InverseKinematics* servant = dynamic_cast< ::RoboCompInverseKinematics::InverseKinematics*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                servant->stop(_m_bodyPart, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        const ::std::string& _m_bodyPart;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompInverseKinematics__InverseKinematics__stop_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(bodyPart, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::RoboCompInverseKinematics::IKException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompInverseKinematics::InverseKinematics::setJoint(const ::std::string& joint, ::Ice::Float angle, ::Ice::Float maxSpeed, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& __p_joint, ::Ice::Float __p_angle, ::Ice::Float __p_maxSpeed, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_joint(__p_joint),
            _m_angle(__p_angle),
            _m_maxSpeed(__p_maxSpeed)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompInverseKinematics::InverseKinematics* servant = dynamic_cast< ::RoboCompInverseKinematics::InverseKinematics*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                servant->setJoint(_m_joint, _m_angle, _m_maxSpeed, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        const ::std::string& _m_joint;
        ::Ice::Float _m_angle;
        ::Ice::Float _m_maxSpeed;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompInverseKinematics__InverseKinematics__setJoint_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(joint, angle, maxSpeed, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::RoboCompInverseKinematics::IKException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompInverseKinematics::InverseKinematics::setFingers(::Ice::Float d, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Float __p_d, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_d(__p_d)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompInverseKinematics::InverseKinematics* servant = dynamic_cast< ::RoboCompInverseKinematics::InverseKinematics*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                servant->setFingers(_m_d, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        ::Ice::Float _m_d;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompInverseKinematics__InverseKinematics__setFingers_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(d, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::RoboCompInverseKinematics::IKException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* RoboCompInverseKinematics::upCast(::RoboCompInverseKinematics::InverseKinematics* p) { return p; }

namespace
{
const ::std::string __RoboCompInverseKinematics__InverseKinematics_ids[2] =
{
    "::Ice::Object",
    "::RoboCompInverseKinematics::InverseKinematics"
};

}

bool
RoboCompInverseKinematics::InverseKinematics::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompInverseKinematics__InverseKinematics_ids, __RoboCompInverseKinematics__InverseKinematics_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompInverseKinematics::InverseKinematics::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompInverseKinematics__InverseKinematics_ids[0], &__RoboCompInverseKinematics__InverseKinematics_ids[2]);
}

const ::std::string&
RoboCompInverseKinematics::InverseKinematics::ice_id(const ::Ice::Current&) const
{
    return __RoboCompInverseKinematics__InverseKinematics_ids[1];
}

const ::std::string&
RoboCompInverseKinematics::InverseKinematics::ice_staticId()
{
    return __RoboCompInverseKinematics__InverseKinematics_ids[1];
}

::Ice::DispatchStatus
RoboCompInverseKinematics::InverseKinematics::___getTargetState(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string bodyPart;
    ::Ice::Int targetID;
    __is->read(bodyPart);
    __is->read(targetID);
    __inS.endReadParams();
    ::RoboCompInverseKinematics::TargetState __ret = getTargetState(bodyPart, targetID, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompInverseKinematics::InverseKinematics::___setTargetPose6D(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string bodyPart;
    ::RoboCompInverseKinematics::Pose6D target;
    ::RoboCompInverseKinematics::WeightVector weights;
    __is->read(bodyPart);
    __is->read(target);
    __is->read(weights);
    __inS.endReadParams();
    try
    {
        ::Ice::Int __ret = setTargetPose6D(bodyPart, target, weights, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__ret);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompInverseKinematics::IKException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompInverseKinematics::InverseKinematics::___setTargetAlignaxis(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string bodyPart;
    ::RoboCompInverseKinematics::Pose6D target;
    ::RoboCompInverseKinematics::Axis ax;
    __is->read(bodyPart);
    __is->read(target);
    __is->read(ax);
    __inS.endReadParams();
    try
    {
        ::Ice::Int __ret = setTargetAlignaxis(bodyPart, target, ax, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__ret);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompInverseKinematics::IKException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompInverseKinematics::InverseKinematics::___setTargetAdvanceAxis(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string bodyPart;
    ::RoboCompInverseKinematics::Axis ax;
    ::Ice::Float dist;
    __is->read(bodyPart);
    __is->read(ax);
    __is->read(dist);
    __inS.endReadParams();
    try
    {
        ::Ice::Int __ret = setTargetAdvanceAxis(bodyPart, ax, dist, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__ret);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompInverseKinematics::IKException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompInverseKinematics::InverseKinematics::___getPartState(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string bodyPart;
    __is->read(bodyPart);
    __inS.endReadParams();
    try
    {
        bool __ret = getPartState(bodyPart, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__ret);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompInverseKinematics::IKException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompInverseKinematics::InverseKinematics::___goHome(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string bodyPart;
    __is->read(bodyPart);
    __inS.endReadParams();
    try
    {
        goHome(bodyPart, __current);
        __inS.__writeEmptyParams();
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompInverseKinematics::IKException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompInverseKinematics::InverseKinematics::___stop(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string bodyPart;
    __is->read(bodyPart);
    __inS.endReadParams();
    try
    {
        stop(bodyPart, __current);
        __inS.__writeEmptyParams();
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompInverseKinematics::IKException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompInverseKinematics::InverseKinematics::___setJoint(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string joint;
    ::Ice::Float angle;
    ::Ice::Float maxSpeed;
    __is->read(joint);
    __is->read(angle);
    __is->read(maxSpeed);
    __inS.endReadParams();
    try
    {
        setJoint(joint, angle, maxSpeed, __current);
        __inS.__writeEmptyParams();
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompInverseKinematics::IKException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompInverseKinematics::InverseKinematics::___setFingers(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Float d;
    __is->read(d);
    __inS.endReadParams();
    try
    {
        setFingers(d, __current);
        __inS.__writeEmptyParams();
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompInverseKinematics::IKException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

namespace
{
const ::std::string __RoboCompInverseKinematics__InverseKinematics_all[] =
{
    "getPartState",
    "getTargetState",
    "goHome",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setFingers",
    "setJoint",
    "setTargetAdvanceAxis",
    "setTargetAlignaxis",
    "setTargetPose6D",
    "stop"
};

}

::Ice::DispatchStatus
RoboCompInverseKinematics::InverseKinematics::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompInverseKinematics__InverseKinematics_all, __RoboCompInverseKinematics__InverseKinematics_all + 13, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompInverseKinematics__InverseKinematics_all)
    {
        case 0:
        {
            return ___getPartState(in, current);
        }
        case 1:
        {
            return ___getTargetState(in, current);
        }
        case 2:
        {
            return ___goHome(in, current);
        }
        case 3:
        {
            return ___ice_id(in, current);
        }
        case 4:
        {
            return ___ice_ids(in, current);
        }
        case 5:
        {
            return ___ice_isA(in, current);
        }
        case 6:
        {
            return ___ice_ping(in, current);
        }
        case 7:
        {
            return ___setFingers(in, current);
        }
        case 8:
        {
            return ___setJoint(in, current);
        }
        case 9:
        {
            return ___setTargetAdvanceAxis(in, current);
        }
        case 10:
        {
            return ___setTargetAlignaxis(in, current);
        }
        case 11:
        {
            return ___setTargetPose6D(in, current);
        }
        case 12:
        {
            return ___stop(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompInverseKinematics::InverseKinematics::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompInverseKinematics::InverseKinematics::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompInverseKinematics::__patch(InverseKinematicsPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompInverseKinematics::InverseKinematicsPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompInverseKinematics::InverseKinematics::ice_staticId(), v);
    }
}
