# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mainUI.ui'
#
# Created: Fri May  8 09:24:08 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_guiDlg(object):
    def setupUi(self, guiDlg):
        guiDlg.setObjectName("guiDlg")
        guiDlg.resize(601, 334)
        self.verticalLayout_6 = QtGui.QVBoxLayout(guiDlg)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtGui.QTabWidget(guiDlg)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botonArriba_L = QtGui.QPushButton(self.tab_3)
        self.botonArriba_L.setObjectName("botonArriba_L")
        self.horizontalLayout.addWidget(self.botonArriba_L)
        self.botonAbajo_L = QtGui.QPushButton(self.tab_3)
        self.botonAbajo_L.setObjectName("botonAbajo_L")
        self.horizontalLayout.addWidget(self.botonAbajo_L)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.botonArriba_R = QtGui.QPushButton(self.tab_3)
        self.botonArriba_R.setObjectName("botonArriba_R")
        self.horizontalLayout_2.addWidget(self.botonArriba_R)
        self.botonAbajo_R = QtGui.QPushButton(self.tab_3)
        self.botonAbajo_R.setObjectName("botonAbajo_R")
        self.horizontalLayout_2.addWidget(self.botonAbajo_R)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.line_2 = QtGui.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.botonAbrir = QtGui.QPushButton(self.tab_3)
        self.botonAbrir.setObjectName("botonAbrir")
        self.horizontalLayout_3.addWidget(self.botonAbrir)
        self.botonCerrar = QtGui.QPushButton(self.tab_3)
        self.botonCerrar.setObjectName("botonCerrar")
        self.horizontalLayout_3.addWidget(self.botonCerrar)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line_3 = QtGui.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.botonBrazo = QtGui.QPushButton(self.tab_3)
        self.botonBrazo.setObjectName("botonBrazo")
        self.verticalLayout.addWidget(self.botonBrazo)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.botonRotacion = QtGui.QPushButton(self.tab_4)
        self.botonRotacion.setObjectName("botonRotacion")
        self.horizontalLayout_4.addWidget(self.botonRotacion)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.botonTraslacion = QtGui.QPushButton(self.tab_4)
        self.botonTraslacion.setObjectName("botonTraslacion")
        self.horizontalLayout_5.addWidget(self.botonTraslacion)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.line_4 = QtGui.QFrame(self.tab_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.botonHome = QtGui.QPushButton(self.tab_4)
        self.botonHome.setObjectName("botonHome")
        self.verticalLayout_5.addWidget(self.botonHome)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_55 = QtGui.QWidget()
        self.tab_55.setObjectName("tab_55")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_55)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.botonCargar = QtGui.QPushButton(self.tab_55)
        self.botonCargar.setObjectName("botonCargar")
        self.verticalLayout_12.addWidget(self.botonCargar)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelCubo1 = QtGui.QLabel(self.tab_55)
        self.labelCubo1.setObjectName("labelCubo1")
        self.horizontalLayout_10.addWidget(self.labelCubo1)
        self.botonIR1 = QtGui.QPushButton(self.tab_55)
        self.botonIR1.setEnabled(False)
        self.botonIR1.setCheckable(False)
        self.botonIR1.setObjectName("botonIR1")
        self.horizontalLayout_10.addWidget(self.botonIR1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelCubo2 = QtGui.QLabel(self.tab_55)
        self.labelCubo2.setObjectName("labelCubo2")
        self.horizontalLayout_11.addWidget(self.labelCubo2)
        self.botonIR2 = QtGui.QPushButton(self.tab_55)
        self.botonIR2.setEnabled(False)
        self.botonIR2.setObjectName("botonIR2")
        self.horizontalLayout_11.addWidget(self.botonIR2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelCubo3 = QtGui.QLabel(self.tab_55)
        self.labelCubo3.setObjectName("labelCubo3")
        self.horizontalLayout_12.addWidget(self.labelCubo3)
        self.botonIR3 = QtGui.QPushButton(self.tab_55)
        self.botonIR3.setEnabled(False)
        self.botonIR3.setObjectName("botonIR3")
        self.horizontalLayout_12.addWidget(self.botonIR3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.tab_55, "")
        self.verticalLayout_6.addWidget(self.tabWidget)

        self.retranslateUi(guiDlg)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(guiDlg)

    def retranslateUi(self, guiDlg):
        guiDlg.setWindowTitle(QtGui.QApplication.translate("guiDlg", "mueveBrazo", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("guiDlg", "Brazo Izquierdo:", None, QtGui.QApplication.UnicodeUTF8))
        self.botonArriba_L.setText(QtGui.QApplication.translate("guiDlg", "arriba_L", None, QtGui.QApplication.UnicodeUTF8))
        self.botonAbajo_L.setText(QtGui.QApplication.translate("guiDlg", "abajo_L", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("guiDlg", "Brazo Derecho:", None, QtGui.QApplication.UnicodeUTF8))
        self.botonArriba_R.setText(QtGui.QApplication.translate("guiDlg", "arriba_R", None, QtGui.QApplication.UnicodeUTF8))
        self.botonAbajo_R.setText(QtGui.QApplication.translate("guiDlg", "abajo_R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("guiDlg", "Mano Derecha:", None, QtGui.QApplication.UnicodeUTF8))
        self.botonAbrir.setText(QtGui.QApplication.translate("guiDlg", "abrir", None, QtGui.QApplication.UnicodeUTF8))
        self.botonCerrar.setText(QtGui.QApplication.translate("guiDlg", "cerrar", None, QtGui.QApplication.UnicodeUTF8))
        self.botonBrazo.setText(QtGui.QApplication.translate("guiDlg", "BRAZO DERECHO", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("guiDlg", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("guiDlg", "Target: [0, 700, 500, 0, 0, 0]", None, QtGui.QApplication.UnicodeUTF8))
        self.botonRotacion.setText(QtGui.QApplication.translate("guiDlg", "conRotacion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("guiDlg", "Target: [0, 700, 500]", None, QtGui.QApplication.UnicodeUTF8))
        self.botonTraslacion.setText(QtGui.QApplication.translate("guiDlg", "sinRotacion", None, QtGui.QApplication.UnicodeUTF8))
        self.botonHome.setText(QtGui.QApplication.translate("guiDlg", "go Home", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("guiDlg", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.botonCargar.setText(QtGui.QApplication.translate("guiDlg", "Cargar cubos", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCubo1.setText(QtGui.QApplication.translate("guiDlg", "Cubo A: [TX,   TY,   TZ,      RX,   RY,   RZ]", None, QtGui.QApplication.UnicodeUTF8))
        self.botonIR1.setText(QtGui.QApplication.translate("guiDlg", "ir 1", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCubo2.setText(QtGui.QApplication.translate("guiDlg", "Cubo B: [TX,   TY,   TZ,      RX,   RY,   RZ]", None, QtGui.QApplication.UnicodeUTF8))
        self.botonIR2.setText(QtGui.QApplication.translate("guiDlg", "ir 2", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCubo3.setText(QtGui.QApplication.translate("guiDlg", "Cubo C: [TX,   TY,   TZ,      RX,   RY,   RZ]", None, QtGui.QApplication.UnicodeUTF8))
        self.botonIR3.setText(QtGui.QApplication.translate("guiDlg", "ir 3", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_55), QtGui.QApplication.translate("guiDlg", "Tab 3", None, QtGui.QApplication.UnicodeUTF8))

