# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mainUI.ui'
#
# Created: Fri Mar 20 09:28:20 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_guiDlg(object):
    def setupUi(self, guiDlg):
        guiDlg.setObjectName("guiDlg")
        guiDlg.resize(460, 275)
        self.verticalLayout_6 = QtGui.QVBoxLayout(guiDlg)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(guiDlg)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botonArriba_L = QtGui.QPushButton(guiDlg)
        self.botonArriba_L.setObjectName("botonArriba_L")
        self.horizontalLayout.addWidget(self.botonArriba_L)
        self.botonAbajo_L = QtGui.QPushButton(guiDlg)
        self.botonAbajo_L.setObjectName("botonAbajo_L")
        self.horizontalLayout.addWidget(self.botonAbajo_L)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(guiDlg)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtGui.QLabel(guiDlg)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.botonArriba_R = QtGui.QPushButton(guiDlg)
        self.botonArriba_R.setObjectName("botonArriba_R")
        self.horizontalLayout_2.addWidget(self.botonArriba_R)
        self.botonAbajo_R = QtGui.QPushButton(guiDlg)
        self.botonAbajo_R.setObjectName("botonAbajo_R")
        self.horizontalLayout_2.addWidget(self.botonAbajo_R)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.line_2 = QtGui.QFrame(guiDlg)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtGui.QLabel(guiDlg)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.botonAbrir = QtGui.QPushButton(guiDlg)
        self.botonAbrir.setObjectName("botonAbrir")
        self.horizontalLayout_3.addWidget(self.botonAbrir)
        self.botonCerrar = QtGui.QPushButton(guiDlg)
        self.botonCerrar.setObjectName("botonCerrar")
        self.horizontalLayout_3.addWidget(self.botonCerrar)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.line_3 = QtGui.QFrame(guiDlg)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.botonBrazo = QtGui.QPushButton(guiDlg)
        self.botonBrazo.setObjectName("botonBrazo")
        self.verticalLayout_6.addWidget(self.botonBrazo)

        self.retranslateUi(guiDlg)
        QtCore.QMetaObject.connectSlotsByName(guiDlg)

    def retranslateUi(self, guiDlg):
        guiDlg.setWindowTitle(QtGui.QApplication.translate("guiDlg", "mueveBrazo", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("guiDlg", "Brazo Izquierdo:", None, QtGui.QApplication.UnicodeUTF8))
        self.botonArriba_L.setText(QtGui.QApplication.translate("guiDlg", "arriba_L", None, QtGui.QApplication.UnicodeUTF8))
        self.botonAbajo_L.setText(QtGui.QApplication.translate("guiDlg", "abajo_L", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("guiDlg", "Brazo Derecho:", None, QtGui.QApplication.UnicodeUTF8))
        self.botonArriba_R.setText(QtGui.QApplication.translate("guiDlg", "arriba_R", None, QtGui.QApplication.UnicodeUTF8))
        self.botonAbajo_R.setText(QtGui.QApplication.translate("guiDlg", "abajo_R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("guiDlg", "Mano Derecha:", None, QtGui.QApplication.UnicodeUTF8))
        self.botonAbrir.setText(QtGui.QApplication.translate("guiDlg", "abrir", None, QtGui.QApplication.UnicodeUTF8))
        self.botonCerrar.setText(QtGui.QApplication.translate("guiDlg", "cerrar", None, QtGui.QApplication.UnicodeUTF8))
        self.botonBrazo.setText(QtGui.QApplication.translate("guiDlg", "BRAZO DERECHO", None, QtGui.QApplication.UnicodeUTF8))

